# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
  transaction-service:
    url: ${TRANSACTION_SERVICE_URL:http://localhost:8082}
  ocr-service:
    url: ${OCR_SERVICE_URL:http://localhost:8083}
  budget-service:
    url: ${BUDGET_SERVICE_URL:http://localhost:8084}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}

# Common Kafka configuration
kafka:
  topics:
    transactions: transactions
    budget-alerts: budget-alerts
    notifications: notifications