server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:auth-postgres}:${DB_PORT:5432}/${DB_NAME:auth_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    # show-sql: true
    
keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:coinsight-realm}
  resource: ${KEYCLOAK_CLIENT:auth-service}
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:OgRK7as6bjDxNKT5qpAbAtaMKsg7c1bh}
