server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:file:///tmp/config-repo}
          default-label: main
          search-paths: '{application}'
    vault:
      enabled: false
      # uri: ${VAULT_URI:http://vault:8200}
      # authentication: token
      # token: ${VAULT_TOKEN:myroot}
      # kv:
      #   enabled: true
      #   backend: secret
      #   default-context: application

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
