server:
  port: 8083
  # Add timeout configurations
  servlet:
    session:
      timeout: 30s
  tomcat:
    connection-timeout: 30000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:coinsight-realm}
  # HTTP timeout configurations
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    async:
      request-timeout: 30000

# Azure Form Recognizer configuration
azure:
  form-recognizer:
    endpoint: ${AZURE_FORM_RECOGNIZER_ENDPOINT:https://coinsight-ocr.cognitiveservices.azure.com/}
    api-key: ${AZURE_FORM_RECOGNIZER_API_KEY:2G2FhKKSMQIGInRgpEYKYZIrsHeJKPLPrLS9e6vnSJgu4LJwFM0tJQQJ99BEACqBBLyXJ3w3AAAAACOG0aZg}
    # Add timeout configurations for Azure client
    timeout:
      connection: 10000  # 10 seconds
      read: 30000       # 30 seconds  
      response: 30000   # 30 seconds
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT:https://rihla-maz4futt-eastus2.cognitiveservices.azure.com/}
    api-key: ${AZURE_OPENAI_API_KEY:1IqZw7IsgY8qzgwH3XAxcEGp7qBCQThKmmo8VJVIL0Ics6jwZbScJQQJ99BEACHYHv6XJ3w3AAAAACOGxchg}
    deployment-id: ${AZURE_OPENAI_DEPLOYMENT_ID:gpt-4.1}
    # Add timeout configurations for OpenAI client
    timeout:
      connection: 10000  # 10 seconds
      read: 60000       # 60 seconds for AI processing
      response: 60000   # 60 seconds

# HTTP client timeout configurations
http:
  client:
    timeout:
      connection: 10000    # 10 seconds
      read: 30000         # 30 seconds
      write: 30000        # 30 seconds

# Service URLs for communication
services:
  transaction:
    url: ${TRANSACTION_SERVICE_URL:http://transaction-service:8081}
    endpoints:
      create: /api/transactions
      categories: /api/transaction-categories

# Keycloak configuration
keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:coinsight-realm}
  resource: ${KEYCLOAK_CLIENT:ocr-service}
  public-client: false
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:epNXpJWhzUqwH87VxspGLXh2hgC2mBkn}

# Logging configuration
logging:
  level:
    id.co.bankbsi.coinsight.transaction: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      processReceipt:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        # Add timeout to prevent hanging calls
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 30000  # 30 seconds
        minimumNumberOfCalls: 3
  timelimiter:
    instances:
      processReceipt:
        timeoutDuration: 30s
        cancelRunningFuture: true

