server:
  port: 8083

spring:
  application:
    name: ocr-service
  cloud:
    vault:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://coinsight-platform-keycloak.coinsight.svc.cluster.local}/realms/${KEYCLOAK_REALM:coinsight-realm}

# Service URLs for communication
services:
  transaction-service:
    url: ${TRANSACTION_SERVICE_URL:http://transaction-service.coinsight.svc.cluster.local:8082}

resilience4j:
  circuitbreaker:
    instances:
      processReceipt:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    id.co.bankbsi.coinsight.ocr: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO