server:
  port: 8083

spring:
  application:
    name: ocr-service
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    vault:
      enabled: true
    config:
      fail-fast: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8090}/realms/${KEYCLOAK_REALM:coinsight-realm}

# azure:
#   form-recognizer:
#     endpoint: ${AZURE_FORM_RECOGNIZER_ENDPOINT}
#     api-key: ${AZURE_FORM_RECOGNIZER_API_KEY}

# services:
#   transaction-service:
#     url: ${TRANSACTION_SERVICE_URL:http://localhost:8082}

resilience4j:
  circuitbreaker:
    instances:
      processReceipt:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    id.co.bankbsi.coinsight.ocr: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO