{{- if .Values.mailhog.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coinsight-platform.fullname" . }}-mailhog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coinsight-platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mailhog
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailhog
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: mailhog
        image: {{ .Values.mailhog.image.repository }}:{{ .Values.mailhog.image.tag }}
        imagePullPolicy: {{ .Values.mailhog.image.pullPolicy }}
        ports:
        - name: smtp
          containerPort: 1025
          protocol: TCP
        - name: http
          containerPort: 8025
          protocol: TCP
        resources:
          {{- toYaml .Values.mailhog.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coinsight-platform.fullname" . }}-mailhog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coinsight-platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: mailhog
spec:
  type: {{ .Values.mailhog.service.type }}
  ports:
  - port: 1025
    targetPort: smtp
    protocol: TCP
    name: smtp
  - port: 8025
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.mailhog.service.type "NodePort") .Values.mailhog.service.nodePort }}
    nodePort: {{ .Values.mailhog.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
