{{- if .Values.secrets.enabled }}
---
# Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coinsight-platform.labels" . | nindent 4 }}
type: Opaque
data:
  # PostgreSQL credentials (base64 encoded)
  postgres-username: {{ .Values.secrets.database.username | b64enc | quote }}
  postgres-password: {{ .Values.secrets.database.password | b64enc | quote }}

---
# Keycloak Secrets
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coinsight-platform.labels" . | nindent 4 }}
type: Opaque
data:
  # Keycloak client secrets (base64 encoded)
  auth-service-secret: {{ .Values.secrets.keycloak.authServiceSecret | b64enc | quote }}
  transaction-service-secret: {{ .Values.secrets.keycloak.transactionServiceSecret | b64enc | quote }}
  ocr-service-secret: {{ .Values.secrets.keycloak.ocrServiceSecret | b64enc | quote }}
  budget-service-secret: {{ .Values.secrets.keycloak.budgetServiceSecret | b64enc | quote }}
  notification-service-secret: {{ .Values.secrets.keycloak.notificationServiceSecret | b64enc | quote }}
  gateway-client-secret: {{ .Values.secrets.keycloak.gatewayClientSecret | b64enc | quote }}

---
# Azure Secrets (for OCR service)
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coinsight-platform.labels" . | nindent 4 }}
type: Opaque
data:
  # Azure API keys (base64 encoded)
  form-recognizer-api-key: {{ .Values.secrets.azure.formRecognizerApiKey | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.azure.openaiApiKey | b64enc | quote }}

---
# Mail Secrets (for notification service)
apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coinsight-platform.labels" . | nindent 4 }}
type: Opaque
data:
  # Mail credentials (base64 encoded)
  mail-username: {{ .Values.secrets.mail.username | b64enc | quote }}
  mail-password: {{ .Values.secrets.mail.password | b64enc | quote }}
{{- end }}
