# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    tags:
      application: ${spring.application.name}
      environment: kubernetes

# Logging configuration for Loki
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  level:
    root: INFO
    id.co.bankbsi.coinsight: DEBUG

services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://auth-service.coinsight.svc.cluster.local:8081}
  transaction-service:
    url: ${TRANSACTION_SERVICE_URL:http://transaction-service.coinsight.svc.cluster.local:8082}
  ocr-service:
    url: ${OCR_SERVICE_URL:http://ocr-service.coinsight.svc.cluster.local:8083}
  budget-service:
    url: ${BUDGET_SERVICE_URL:http://budget-service.coinsight.svc.cluster.local:8084}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service.coinsight.svc.cluster.local:8085}

# Common Kafka configuration
kafka:
  topics:
    transactions: transactions
    budget-alerts: budget-alerts
    notifications: notifications