# application.yml
server:
  port: 8888

spring:
  application:
    name: config-server
  main: 
    allow-bean-definition-overriding: true
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_URI:file:///tmp/config-repo}
    vault:
      enabled: true
      host: vault
      port: 8200
      scheme: http
      uri: ${VAULT_URI:http://vault:8200}
      authentication: token
      token: ${VAULT_TOKEN:myroot}
      kv:
        enabled: true
        backend: secret
        default-context: application
